# Generated by Django 6.0.3 on 2026-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rent_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
