# Generated by Django 5.1.2 on 2026-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_post_rent_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="post",
            name="onlyfor_female",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="onlyfor_male",
            field=models.BooleanField(default=False),
        ),
    ]
